"""empty message

Revision ID: bf817ad7a211
Revises: 1eadc4d03ecb
Create Date: 2024-12-09 23:06:04.822661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf817ad7a211'
down_revision = '1eadc4d03ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_task', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.drop_column('id_task')

    # ### end Alembic commands ###
